version: '3'
services:

  post-api:
    container_name: "post-api"
    image: ghcr.io/manumasjoan/post-service:master
    ports:
      - '8080:8080'
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: post-db
      DB_HOST: post
      DB_PORT: 5423

  post-db:
    image: postgres:12.9
    restart: always
    ports:
      - '5423:5423'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=post-db
    volumes:
      - pgdata:/var/lib/postgresql/data


  follow-api:
    container_name: "follow-api"
    image: ghcr.io/tefiporacchia/followservice:master
    ports:
      - '8081:8080'
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: follow-db
      DB_HOST: postgres_db
      DB_PORT: 5423

  follow-db:
    image: postgres:12.9
    restart: always
    ports:
      - '5424:5423'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=follow-db
    volumes:
      - pgdata:/var/lib/postgresql/data


  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - '8082:8080'
    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    container_name: "keycloak-postgres"
    image: postgres:12.9
    restart: always
    ports:
        - '5422:5423'
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=keycloak-db

volumes:
  pgdata:
    external: false